{% set name = "django-bootstrap4" %}
{% set version = "1.0.0" %}
{% set sha256 = "c7d7f89e59eb5b702da0fd44438094f20e8f174970e64afece124f38cb4f3aee" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - django >=1.11

test:
  imports:
    - bootstrap4
    - bootstrap4.templatetags
    
about:
  home: 'https://github.com/zostera/django-bootstrap4'
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: Bootstrap 4 integration with Django.
  description:  Write Django as usual, and let django-bootstrap4 make template output into Bootstrap 4 code.  
  doc_url: http://django-bootstrap4.readthedocs.io/
  dev_url: https://github.com/zostera/django-bootstrap4

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
