travis:
  secure:
    BINSTAR_TOKEN: rgDqdGQpgsO8XA+o53yQLcfIEuzLjza+MuULH6mK0Fid3aQEUq3NPxHrPBwWrk6R9bm83SGkDMJa1w+XV+mb2CRLV9Sg1o08ZxcSPCdGupepaH6vO2A12msjxsU+7RZ2anl69C0Ym0GjvPrUZtioKpt1XRhKQgAgu/DnnUb9GT81w2yyiGiV4C1XrYY1TB8yO0PbtVscrOME9wDPLXr0GfuszjY2FkNLru1h6f//h2O84P0lLXxotFywe/w/c0o8Gb+Scu/HaHHtLA9gEQp2t+4ONkyqYtnSz2XZtiV2N7DU8Zk+sgegw2Z/unIn0xRkW4AqSd5T+MBls9yrkh/+qxb0LvTtteqF1QQCgEH+3rHqY+m37C06vQrQZgpTl/l8trK2kqSFlb5KoUy98d6+qAxrpdn8+2AvrWerCIlRXnL+Net4Y+Zbx04PgscCLwwvhlIcgr3C3uHXC4lLNa1vHeYswsiLqHUTrXlxmeqDDZyDkVqNg+CJZ9tk/FGy723tIKBMgwT9uGsDsT9W5LqW0GuPq7C1wB5IFQQI1OwjKtMtY7Pd58hSKv9PckwsFK/b+27jrpzkjK5cgoUGdCkNF5hizm/9w0XIWz/Jd3TnIkMtx8DwnQrwtwhDgwF143xnJvcY+mPV/jf57gPtenQd5Lv8dVzxiM5lI00hq3Qi/Vc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
