travis:
  secure:
    BINSTAR_TOKEN: aRvyKqft+6gNUa2GW/w/YplmP9pWBI7uke+TVYFmmlxwrJ0RtJkUXiYX1z6syTdDOBMCWfY0W5Pjg17UFfnSagKFFmnGGbj0pXi9uDNPFNGKU0z/V5qf2sD9y29D+Ci2Otv5+ForgJw0Jq0ogMPPLN0uwKxmTJuSxvIGbd9Qthu2pdWsOE6HLrp97ywTDE7pkpiss5KHChZuycIrfKiGsUR6OxL3LvolD4lk5OjJr7RXlZZk02kBzOopHo9iiIup7Evizhh2gDY9PEKlt9PK/CdSSQZxibvXJmFKccIiFUpp/8WMiU93g3/JUNqxCfjN/qO+a0Clqr995L8HcquZXjSNw2+9UstzrGAsiZflr3X3qYpXbrT8xYEXgktf8lnm+HIXwNEcznFF1SPxbOVTU2n2otLapGeLxMEU5wvnkd7mB9u53mmEG/rCXuCTdPMvnIgALSyjnPNPva+o9/R6RgTLVOGXOOUMNQMF+17y9nEyCLDnwmWb8YQ5L/mnhEKcoxlDWgadCNiC8PTXG/YHqrRhomAhcgDI0Cb+oqQ8uzgrg8QUnDLi+mjDKW4lrbziRplyxUZwqhI1zHclv1oycoPc1vHRGFNbY+dY4d3y1LQmXmOLepiq0Agid/+90YyXSacfQUooeA+C9Zb7HoFgv4IWP/itIC9lRD6v15kxMj0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
